# Generated by Django 2.0.4 on 2018-04-29 14:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2018, 4, 29, 14, 34, 13, 316717, tzinfo=utc))),
                ('mod_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
