# Generated by Django 2.0.4 on 2018-05-18 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mod_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField(blank=True, max_length=100000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HoldApp.Case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HoldApp.Case')),
            ],
        ),
        migrations.CreateModel(
            name='DModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DModelD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dval', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DModelF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fval', models.FloatField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GroupRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mod_date', models.DateTimeField(blank=True, null=True)),
                ('group', models.CharField(choices=[('U', 'User'), ('C', 'Contributor')], default='U', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HModelData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data1', models.CharField(max_length=100)),
                ('data2', models.CharField(max_length=100)),
                ('data3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HModelStuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuff1', models.CharField(max_length=100)),
                ('stuff2', models.CharField(max_length=100)),
                ('stuff3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mod_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('pdf', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hmodel',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HoldApp.HModelData'),
        ),
        migrations.AddField(
            model_name='hmodel',
            name='stuff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HoldApp.HModelStuff'),
        ),
        migrations.AddField(
            model_name='dmodel',
            name='dval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HoldApp.DModelD'),
        ),
        migrations.AddField(
            model_name='dmodel',
            name='fval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HoldApp.DModelF'),
        ),
        migrations.AddField(
            model_name='caseh',
            name='hmodel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HoldApp.HModel'),
        ),
        migrations.AddField(
            model_name='caseh',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HoldApp.Report'),
        ),
        migrations.AddField(
            model_name='cased',
            name='dmodel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HoldApp.DModel'),
        ),
        migrations.AddField(
            model_name='cased',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HoldApp.Report'),
        ),
    ]
