# Generated by Django 2.0.4 on 2018-05-18 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HoldApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='title',
            new_name='reporttitle',
        ),
    ]
