# Generated by Django 2.0.4 on 2018-04-29 14:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HoldApp', '0002_auto_20180429_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 14, 41, 53, 393583, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 14, 41, 53, 393583, tzinfo=utc)),
        ),
    ]
